#-----------------------------------------------------------------------

APP       := ServerEngine
TARGET    :=
CONFIG    := 
STRIP_FLAG:= N
INCLUDE   := -I../../Common/CommJce/ -I../../Cluster/OssServer/
LIB       :=
LOCAL_SRC :=

#-----------------------------------------------------------------------
include /home/tafjce/ServerEngine/DALComm/DALComm.mk
include /home/mage/Documents/tool/taf/makefile.taf
#-----------------------------------------------------------------------
