
#-----------------------------------------------------------------------

APP       := Aegis
TARGET    := 
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   += -I/usr/local/mqq/wbl/include 
LIB       += -L/usr/local/mqq/wbl/lib -lwbl

#-----------------------------------------------------------------------

include /home/mage/Documents/tool/taf/makefile.taf

#-----------------------------------------------------------------------

