LoadFile( "Hero/Hero.lua" );
--LoadFile( "Hero/HeroUpgrade.lua" )
--LoadFile( "Hero/HeroAscendingOrder.lua" )
--LoadFile( "Hero/HeroDetails.lua" )
--LoadFile( "Hero/HeroConvert.lua" )
----LoadFile( "Hero/HeroOrderMaterial.lua" )
----LoadFile( "Hero/HeroSystemFunctionalModule.lua" )
----LoadFile( "Hero/InitHeroSystem.lua" )
--LoadFile( "Hero/HeroSell.lua" )
--LoadFile( "Hero/HeroBatchSell.lua" )
--LoadFile( "Hero/HeroAscendingMatrial.lua" )

--test 
--LoadFile( "Hero/InitHeroConvert.lua" )
--LoadFile( "Hero/NewHeroSystem.lua" )
LoadFile( "Hero/NewHeroEquip.lua" )
LoadFile( "Hero/HeroSystemUseFunction.lua" )
LoadFile( "Hero/HeroListSecond.lua" )
LoadFile( "Hero/HeroCurInfoSecond.lua" )
LoadFile( "Equip/EquipFuben.lua" )