#ifndef __ENTITY_PROPERTY_H__
#define __ENTITY_PROPERTY_H__

#include "PropertyComm.h"
PROP_DEFBEGIN()
	// 所有实体公用的
	PROP_DEFIMP(PROP_ENTITY_NAME, string, 1, "实体名字")

	// 基本属性
	PROP_SIMPLEDEFIMP(PROP_ENTITY_CLASS, int, "实体类型")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_LEVEL, int, "等级")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_ACCOUNT, string, "帐号")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_ROLEPOS, int, "角色位置")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_CREATEFINISH, int, "角色创建完成")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BATTLEPOS, int, "战斗位置")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_FIGHTVALUE, int, "战力")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_JOB, int, "职业")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEID, int, "怪物ID")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ANGER, int, "怒气")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_LEVELSTEP, int, "等阶")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_EXP, int, "经验")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HEROEXP, int, "英雄经验")

	// 连接信息(Actor专用)
	PROP_SIMPLEDEFIMP(PROP_ACTOR_RS, string, "RS地址")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_CON, int, "连接号")
	

	// 生命相关属性
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HP, int, "HP")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_MAXHP, int, "生命上限")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEMAXHP, int, "BASEMAXHP")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_MAXHPAVALUE, int, "生命上限加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_MAXHPAPERCENT, int, "生命上限提高万分比")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HPGROW, int, "英雄生命成长") // 存档数值

	// 攻击相关属性
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ATT, int, "攻击")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEATT, int, "基础攻击")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ATTAVALUE, int, "攻击加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ATTAPERCENT, int, "攻击提高万分比")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ATTGROW, int, "攻击成长")

	// 命中
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HIT, int, "命中值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEHIT, int, "基础命中")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HITAVALUE, int, "命中附加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HITAPERCENT, int, "命中提高万分比")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_HITGROW, int, "命中成长")

	// 闪避
	PROP_SIMPLEDEFIMP(PROP_ENTITY_DOGE, int, "闪避")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEDOGE, int, "基础闪避")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_DOGEAVALUE, int, "闪避附加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_DOGEAPERCENT, int, "闪避提高万分比")

	// 暴击
	PROP_SIMPLEDEFIMP(PROP_ENTITY_KNOCK, int, "暴击")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEKNOCK, int, "基础暴击")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_KNOCKAVALUE, int, "暴击加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_KNOCKAPERCENT, int, "暴击提高万分比")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_KNOCKGROW, int, "暴击成长")

	//韧性(暴抗)
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ANTIKNOCK, int, "韧性")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEANTIKNOCK, int, "基础韧性")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ANTIKNOCKAVALUE, int, "韧性加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ANTIKNOCKAPERCENT, int, "韧性提高万分比")

	// 抵挡
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BLOCK, int, "抵挡")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEBLOCK, int, "基础抵挡")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BLOCKAVALUE, int, "抵挡加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BLOCKAPERCENT, int, "抵挡提高万分比")


	// 破击
	PROP_SIMPLEDEFIMP(PROP_ENTITY_WRECK, int, "破击")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEWRECK, int, "基础破击")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_WRECKAVALUE, int, "破击加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_WRECKAPERCENT, int, "破击提高万分比")


	// 护甲
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ARMOR, int, "护甲")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEARMOR, int, "基础护甲")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ARMORAVALUE, int, "护甲加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ARMORAPERCENT, int, "护甲提高万分比")
	

	// 破甲
	PROP_SIMPLEDEFIMP(PROP_ENTITY_SUNDER, int, "破甲")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASESUNDER, int, "基础破甲")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_SUNDERAVALUE, int, "破甲加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_SUNDERAPERCENT, int, "破甲提高万分比")

	// 初始怒气
	PROP_SIMPLEDEFIMP(PROP_ENTITY_INITANGER, int, "初始怒气")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEINITANGER, int, "基础初始怒气")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_INITANGERAVALUE, int, "初始怒气加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_INITANGERAPERCENT, int, "初始怒气提高万分比")


	// 新英雄标记(英雄特有标记)
	PROP_SIMPLEDEFIMP(PROP_ENTITY_MASTER, int, "主人实体")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_UUID, string, "实体UUID")


	// 特殊效果属性(固定目标选择策略),存在该属性，则无视效果目标策略
	PROP_SIMPLEDEFIMP(PROP_ENTITY_FIXTARGETSELECT, int, "固定目标选择策略")
	
	PROP_SIMPLEDEFIMP(PROP_ENTITY_PHYSTRENGTH, int, "体力")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_PACKFORGHOST, int, "为Ghost打包")

	PROP_SIMPLEDEFIMP(PROP_ACTOR_SILVER, int, "银两")    // 游戏内的货币
	PROP_SIMPLEDEFIMP(PROP_ACTOR_GOLD, int, "元宝")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_FSCHIPCOUNT, int, "武魂碎片数量")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_REPLACEHANDLE, int, "替换句柄") // 用于英雄转换
	PROP_SIMPLEDEFIMP(PROP_HERO_LVSTEPPROGRESS, int, "等阶进度")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_HEROCVTCOUNT, int, "英雄转换次数")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_FUNCTIONMASK, int, "功能开关标志位")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_ISMACHINE, int, "机器人标记")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_VIPLEVEL, int, "VIP等级")

	PROP_SIMPLEDEFIMP(PROP_ACTOR_WORLD, int, "世界ID")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_HONOR, int, "荣誉")

	PROP_SIMPLEDEFIMP(PROP_LAST_PVETIME, int, "上次PVE时间")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_DIZZ, int, "眩晕")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_CONFUSE, int, "混乱")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_SEX, int, "性别")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_CONTINUEKILL, int, "连杀")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_RELIVECOUNT, int, "剩余复活次数")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_COMMSKILL_REPLACETTARGET, int, "普攻目标选择")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_LASTPHYSTRENGTHTIME, int, "上次恢复体力时间")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_PHYSTRENGTHLIMIT, int, "体力上限")

	PROP_SIMPLEDEFIMP(PROP_ACTOR_RECHARGED, int, "玩家是否已经充值过")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ISClOSEATTCOMMUPORNOT, int, "是否已经关闭att上浮提示")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_FIRSTCONSUME, int, "玩家首次消费")
	PROP_SIMPLEDEFIMP(PROP_HERO_HASFIGHTSOUL, int, "英雄是否有武魂")

	//神兽兑换相关
	PROP_SIMPLEDEFIMP(PROP_GODANIMALSOUL_ITEMID, int, "兑换ItemID")
	PROP_SIMPLEDEFIMP(PROP_GODANIMALSOUL_ITEMCOUNT, int, "兑换数量")
	//add by hyf VIPEXP
	PROP_SIMPLEDEFIMP(PROP_ACTOR_VIPEXP,int,"VIP经验")

	//消息通知
	PROP_SIMPLEDEFIMP(PROP_ACTOR_NOTICE,int, "提示位")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_JUSTRELIVE, int, "刚刚复活")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_WRECKGROW, int, "破击成长")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_SKILLDAMAGE, int, "绝技伤害")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_SKILLDEF, int, "绝技防御")

	PROP_SIMPLEDEFIMP(PROP_HERO_HASEQUIP, int, "英雄是否有装备")
	
	PROP_SIMPLEDEFIMP(PROP_HERO_PRICE, int, "英雄价格")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_SAODANGLIMI, int, "扫荡次数限制")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_SAODANGPOINT, int, "扫荡点")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_LASTSAODANG_RESUMETIME, int, "扫荡上次恢复时间")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEPROP_FIXPARAM, int, "属性系数")
	
	PROP_SIMPLEDEFIMP(PROP_ACTER_MAX_FIGHTVALUE, int, "玩家历史最高战力")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_RELIVEENHANCE, int, "复活回血增强万分比")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_REBOUNDPERCENT, int, "反弹能力")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_CONDITIONDEAD, int, "条件死亡能力")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_ACTOR_HEAD, int, "玩家头像")
	
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ACTOR_HEADTYPE, int, "玩家头像类型")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_ACTOR_VIGOR, int, "玩家精力")
	
	PROP_SIMPLEDEFIMP(PROP_ENTITY_KNOCKENHANCEPERCENT, int, "暴击伤害增强万分比")
	
	PROP_SIMPLEDEFIMP(PROP_ENTITY_ENHANCE_VAMPIREPERCENT, int, "吸血增强万分比")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_IMMUNITYDAMAGE, int, "免疫所有伤害")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_TOUCHDEADEFFECT_COUNT, int, "回光返照次数")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_PERCENTDAMAGE_ENHANCE, int, "万分比伤害增强")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_PERCENTDAMAGE_VAMPIREPERCENT, int, "万分比伤害吸血万分比")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_KNOCK_REBACKPERCENT, int, "暴击吸血万分比")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_CONTINUESKILL_RATE, int, "连击率")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_QUALITY, int, "品质")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_SMALLSKILLDAMAGE, int, "小招伤害")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_DEF, int, "防御")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_BASEDEF, int, "基础防御")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_DEFAVALUE, int, "防御加值")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_DEFAPERCENT, int, "防御加成万分比")
	PROP_SIMPLEDEFIMP(PROP_ENTITY_DEFGROW, int, "防御成长")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_FIGHTVALUE_PREFIGHT, int, "战斗前的固定战力")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_PREDEAD_USESKILLFLAG, int, "死亡前释放技能标记")

	PROP_SIMPLEDEFIMP(PROP_ENTITY_STRENGTHBUYTIMES, int, "体力剩余购买次数")

	PROP_SIMPLEDEFIMP(PROP_ACTOR_LEGION_CONTRIBUTE, int, "军团贡献")	 

	PROP_SIMPLEDEFIMP(PROP_ACTOR_SHOWKNOCK_DAMAGE, int, "暴击伤害展示")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_SHOWKNOCK_XIXUE, int, "暴击吸血展示")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_SHOWCONATTACK, int, "连击展示")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_SHOWFIRSTPAY, int, "首充标记")
	PROP_SIMPLEDEFIMP(PROP_ACTOR_ACC_PAYMENT, int, "累积充值")

	


	PROP_SIMPLEDEFIMP(PROP_ENTITY_MAX, int, "属性最大值")

	
	
	
PROP_DEFEND()


#endif
