EMSTag_Map=1
EMSTag_Obj=2
EMStag_Effect=3
EMSTag_Ui=4
EMStag_SimpleChat=20
EMSTag_DungeonEffect=21
EMSTag_GuideLayer=22
EMSTag_Guide_Notice=23
EMSTag_Ide_Notice=24
EMSTag_LevelUp=25
EMSTag_EquipCard=26
EMSTag_EquipCardLook=27
EMSTag_Msg=28
EMSTag_Guide=29
EMSTag_GradeOpen=30
EMSTag_AccomplishTask=31
EMSTag_HaveNewTask=32
EMSTag_PromptBox=33
EMSTag_OtherPromptBox=34
EMSTag_Marquee=35
EMSTag_Waiting=36

EState_Logo=0
EState_MainMenu=1
EState_Gaming=2
EState_End=3

EFormation_Max=9

E_ActionType_Anim=0
E_ActionType_FadeOut=1
E_ActionType_FadeIn=2

EAnimsIdle=0
EAnimsAtt=1
EAnimsAtt2=2
EAnimsHurt=3
EAnimsDoge=4
EAnimsRun=5
EAnimsBack=6
EAnimsAtt3=7
EAnimsMax=8
EAnimsNone=9
EAnimsZiBao=10

EGameState_None=0
EGameState_LoadScene=1
EGameState_MainUi=2
EGameState_MyTerritory=3
EGameState_Territory=4
EGameState_Fighting=5

ESLoadStep_Init=0
ESLoadStep_ServerData=1
ESLoadStep_FreeLastScene=2
ESLoadStep_FreeTexTure=3
ESLoadStep_LoadTileMap=4
ESLoadStep_LoadEnity=5
ESLoadStep_Finished=6
ESLoadStep_SwitchMainMenu=7

EFightState_None=0
EFightState_Init=1
EFightState_PlayStartAnim=2
EFightState_ReadNextAction=3
EFightState_DecodeOneAction=4
EFightState_ReplaceMember=5
EFightState_DecodeOneResultSet=6
EFightState_PlayOneResultSet=7
EFightState_ChgProp=8
EFightState_EndOneResultSet=9
EFightState_EndOneAction=10
EFightState_UI=11
EFightState_End=12
EFightState_Pause=13

EAttackRenderState_None=0
EAttackRenderState_AttEffect=1
EAttackRenderState_AttAnim=2
EAttackRenderState_Move=3
EAttackRenderState_AttAniming=4
EAttackRenderState_BulletEffect=5
EAttackRenderState_ZiBao=6
EAttackRenderState_HurtEffect=7
EAttackRenderState_ZiBaoHurtEffect=8
EAttackRenderState_End=9

EUIOpenType_None=0
EUIOpenType_Dugeon=1
EUIOpenType_Formation=2
EUIOpenType_LegionBoss=3
EUIOpenType_Arena=4
EUIOpenType_LegionFighting=5
EUIOpenType_LastLegionFighting=6
EUIOpenType_CompBattle=7
EUIOpenType_CompBattleResult=8
EUIOpenType_WorldBoss=9
EUIOpenType_Hero=10
EUIOpenType_GodAnim=11
EUIOpenType_FightSoul=12
EUIOpenType_Babel=13
EUIOpenType_NineSky=14
EUIOpenType_EquipFuben=15

EUIOpenAction_None=0
EUIOpenAction_Enlarge=1
EUIOpenAction_MoveIn_Left=2
EUIOpenAction_MoveIn_Right=3
EUIOpenAction_MoveIn_Top=4
EUIOpenAction_MoveIn_Bottom=5
EUIOpenAction_FadeIn=6
EUIOpenAction_Reel=7
EUIOpenAction_Move_Right_Left=8

EUICloseAction_None=0
EUICloseAction_Lessen=1
EUICloseAction_MoveOut_Left=2
EUICloseAction_MoveOut_Right=3
EUICloseAction_MoveOut_Top=4
EUICloseAction_MoveOut_Bottom=5
EUICloseAction_FadeOut=6
EUICloseAction_Reel=7

