EEntityRenderTag_Begin=100
EEntityRenderTag_EntityName=101
EEntityRenderTag_HPBg=102
EEntityRenderTag_AngerBg=103
EEntityRenderTag_HP=104
EEntityRenderTag_Anger=105
EEntityRenderTag_AngerFull=106
EEntityRenderTag_Lvl=107
EEntityRenderTag_ChengHao=108
EEntityRenderTag_SkillEffect=130
EEntityRenderTag_EffectStart=200
EEntityRenderTag_EffectEnd=220

MAX_MAP_HEIGHT=10000

EZorderProperty_BackBg=0

EDirection_Left=0
EDirection_Right=1

ERenderYOffset_Foot=0
ERenderYOffset_HalfBody=1
ERenderYOffset_Head=2

ERenderLayerType_Model=0
ERenderLayerType_Buff=1
ERenderLayerType_Effect=2
ERenderLayerType_UI=3
ERenderLayerType_Max=4

