LoadFile( "OtherFunction/Marquee.lua" )
LoadFile( "OtherFunction/OtherPlayerInfo.lua" )
LoadFile( "OtherFunction/PromptBox.lua" )
LoadFile( "OtherFunction/HeroLevelUpInfo.lua" )
LoadFile( "OtherFunction/GradeOpen.lua" )
LoadFile( "OtherFunction/MyInfoView.lua" )
LoadFile( "OtherFunction/SystemSettings.lua" )
LoadFile( "OtherFunction/MusicConfig.lua" )
LoadFile( "OtherFunction/LogoTipCofig.lua" )
LoadFile( "OtherFunction/NoticeFunction.lua" )
LoadFile( "OtherFunction/ItemTips.lua" )
LoadFile( "OtherFunction/OtherPromptBox.lua" )

LoadFile("OtherFunction/PushMent.lua")
LoadFile( "OtherFunction/SliverTipAndXiuWeiTip.lua" )

