#ifndef __FIGHTSOUL_PROPERTY_H__
#define __FIGHTSOUL_PROPERTY_H__

#include "PropertyComm.h"


PROP_DEFBEGIN()

	PROP_DEFIMP(PROP_FIGHTSOUL_ATT, int, 1, "¹¥»÷")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_MAXHP, int, "ÉúÃü")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_HIT, int, "ÃüÖÐ")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_DOGE, int, "ÉÁ±Ü")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_BLOCK, int, "µÖµ²")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_WRECK, int, "ÆÆ»÷")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_KNOCK, int, "±©»÷")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_ANTIKNOCK, int, "ÈÍÐÔ")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_ARMOR, int, "»¤¼×")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_SUNDER, int, "ÆÆ¼×")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_ANGER, int, "Å­Æø")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_EXP, int, "¾­Ñé")
	
PROP_DEFEND()


#endif
