#ifndef __ITEM_PROPERTY_H__
#define __ITEM_PROPERTY_H__

#include "PropertyComm.h"

PROP_DEFBEGIN()

	// 配置属性
	PROP_DEFIMP(PROP_ITEM_BASEID, int, 1, "道具ID")
	PROP_SIMPLEDEFIMP(PROP_ITEM_LVLLIMIT, int, "等级限制")
	PROP_SIMPLEDEFIMP(PROP_ITEM_TYPE, int, "类型")
	PROP_SIMPLEDEFIMP(PROP_ITEM_QUALITY, int, "品质")
	PROP_SIMPLEDEFIMP(PROP_ITEM_USEEFFECT, int, "使用效果")
	PROP_SIMPLEDEFIMP(PROP_ITEM_SALETYPE, int, "出售类型")
	PROP_SIMPLEDEFIMP(PROP_ITEM_MAXSTACKCOUNT, int, "堆叠上限")
	PROP_SIMPLEDEFIMP(PROP_ITEM_PRICE, int, "物品卖出单价")

	
	PROP_SIMPLEDEFIMP(PROP_EQUIP_POS, int , "装备部位")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_BASEPROP, string, "基础属性")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_SPECIALPROP, string, "特殊属性")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_RANDOMPROP_GROUPID, int, "随机属性组")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_JOBLIMIT, int, "职业限制")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_SCORE, int, "装备评分")

	PROP_SIMPLEDEFIMP(PROP_EQUIP_DROPDESC, string, "掉落地点")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_SELLTYPE, int, "装备出售类型")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_SELLPRICE, int, "装备出售价格")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_DROPSCENE, string, "掉落地点")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_ENHANCE_COSTPARAM, int, "强化消耗系数")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_SPECOAL_DROPSOURCE, string, "特殊掉落地点")


	PROP_SIMPLEDEFIMP(PROP_FAVORITE_PROP, string, "喜好品属性")


	// 动态属性
	PROP_SIMPLEDEFIMP(PROP_ITEM_STACKCOUNT, int, "现有堆叠数量")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_LEVEL, int, "装备等级")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_ENHANCEMONEY, int, "装备强化消耗金钱总数")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_RANDOMPROP, int, "随机属性ID")
	PROP_SIMPLEDEFIMP(PROP_EQUIP_RANDOMVALUE, int, "随机属性数值")

	PROP_SIMPLEDEFIMP(PROP_EQUIP_DROPID, int, "礼包掉落ID")
	
	
PROP_DEFEND()

#endif
